version: '3.1'

services:

  db:
    image: mariadb:10.7.3-focal
    container_name: maria_db
    ports:
      - 3306:3306
    volumes:
      - ${PWD}/mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: udemy_maria_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
